title: My github page leanring module site
author: Ashish Raj
email: ashishraj@azuredevopspro.com
description: > # this means to ignore newlines until "baseurl:"
  This is my Github page website created by learn module.

# social links
twitter_username:ashishraj # DO NOT include the @ character, or else the build will fail!
github_username:  ashishrajsrivastava # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
